server:
   port: 8080
spring:
   data:
      mongodb:
         authentication-database: admin
         database: test
         username: test
         password: "12345" #这个坑好大！
         host: 127.0.0.1
         port: 27017
          #uri: mongodb://test:12345@localhost:27017/test?authSource=admin